# Usa Python 3.11 leggero
FROM python:3.11-slim

WORKDIR /app

# Variabili ambiente per Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Installa dipendenze sistema
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Installa librerie Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia il codice
COPY . .

# CREA LE CARTELLE STATICHE:
# Questo è fondamentale per evitare errori di permessi quando monti il volume
RUN mkdir -p static/videos static/images

# Avvia Uvicorn in modalità PRODUZIONE (senza --reload)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]